export default [
  {
    "login": "kedarvijaykulkarni",
    "id": 46336951,
    "node_id": "MDQ6VXNlcjQ2MzM2OTUx",
    "avatar_url": "https://avatars.githubusercontent.com/u/46336951?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kedarvijaykulkarni",
    "html_url": "https://github.com/kedarvijaykulkarni",
    "followers_url": "https://api.github.com/users/kedarvijaykulkarni/followers",
    "following_url": "https://api.github.com/users/kedarvijaykulkarni/following{/other_user}",
    "gists_url": "https://api.github.com/users/kedarvijaykulkarni/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kedarvijaykulkarni/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kedarvijaykulkarni/subscriptions",
    "organizations_url": "https://api.github.com/users/kedarvijaykulkarni/orgs",
    "repos_url": "https://api.github.com/users/kedarvijaykulkarni/repos",
    "events_url": "https://api.github.com/users/kedarvijaykulkarni/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kedarvijaykulkarni/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Kedar Vijay Kulkarni",
    "company": "@quantumgrad ",
    "blog": "https://www.linkedin.com/in/kedarvijaykulkarni/",
    "location": "Thane, Maharashtra, India",
    "email": null,
    "hireable": true,
    "bio": "An experienced Web developer with over 17 years of experience in all stages of advanced web development. Skilled in frontend solutions.",
    "twitter_username": "kedman1234",
    "public_repos": 38,
    "public_gists": 0,
    "followers": 1,
    "following": 40,
    "created_at": "2019-01-03T04:37:52Z",
    "updated_at": "2022-06-11T09:54:21Z"
  }
];